// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://femproject.com/terms",
        "contact": {
            "name": "Fem Project Support Team",
            "url": "https://femproject.com/support",
            "email": "support@femproject.com"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tokens": {
            "post": {
                "description": "Creates a new user in the system after validating the input.\nThe user must provide a unique username, a valid email address, and a secure password.\nOptionally, a bio can be included for the user's profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Register a new user account",
                "parameters": [
                    {
                        "description": "User Params",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns created user information",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "tokens": {
                                            "$ref": "#/definitions/tokens.Token"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input or bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.Envelope"
                        }
                    },
                    "500": {
                        "description": "Server error while creating the user",
                        "schema": {
                            "$ref": "#/definitions/utils.Envelope"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Creates a new user in the system after validating the input.\nThe user must provide a unique username, a valid email address, and a secure password.\nOptionally, a bio can be included for the user's profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Register a new user account",
                "parameters": [
                    {
                        "description": "User Params",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.registerUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns created user information",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "user": {
                                            "$ref": "#/definitions/store.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input or bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.Envelope"
                        }
                    },
                    "500": {
                        "description": "Server error while creating the user",
                        "schema": {
                            "$ref": "#/definitions/utils.Envelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.createTokenRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.registerUserRequest": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "store.User": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "tokens.Token": {
            "type": "object",
            "properties": {
                "expiry": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "utils.Envelope": {
            "type": "object",
            "additionalProperties": true
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Fem Project API Documentation",
	Description:      "Fem Project is a social and personal empowerment platform built to support users in creating profiles, interacting with features, and managing their accounts seamlessly.\nThis backend API provides secure endpoints for user registration, authentication, account management, and future social features.\nAll responses are formatted using JSON and follow RESTful standards.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
